"""
Cloud Server Entity Module
============================
Models the honest-but-curious cloud server that stores encrypted
aggregate outputs and performs signature verification.

Paper Reference:
  - System Model: "The cloud server provides long-term storage, archival
    services, and analytical processing over aggregated data."
  - "The cloud is considered honest-but-curious and receives only
    encrypted aggregate outputs generated by fog nodes."
  - Phase V, Step 1: Cloud stores (T_i(t), σ_i(t)) after verification
"""

from typing import Dict, List, Tuple, Any, Optional

from src.crypto.tee import compute_hash


class CloudServer:
    """
    Cloud Server entity (C).

    Honest-but-curious: correctly stores aggregated ciphertexts and
    executes requested operations but may attempt to infer sensitive
    information from received data.
    """

    def __init__(self):
        """Initialize cloud server with empty storage."""
        # Storage: epoch → fog_id → (T_i(t), σ_i(t))
        self.storage: Dict[int, Dict[int, dict]] = {}

        # Verification results log
        self.verification_log: List[dict] = []

    def receive_and_verify(self, fog_node_id: int, epoch: int,
                            aggregation_package: dict,
                            signature: bytes,
                            tee_enclave) -> bool:
        """
        Receive and verify an aggregation commitment from a fog node.

        Process:
        1. Receive T_i(t) = (C_i^{final}, Mode_i, Rel_i, RecStatus_i)
        2. Verify σ_i(t) = Sign_{sk_i^TEE}(H(T_i(t)))
        3. Store only after successful verification

        Args:
            fog_node_id: ID of the submitting fog node.
            epoch: Current aggregation epoch.
            aggregation_package: T_i(t) dict with keys:
                - 'final_aggregate': C_i^{final}
                - 'mode': Mode_i(t)
                - 'reliability': Rel_i(t+1)
                - 'recovery_status': RecStatus_i(t)
            signature: σ_i(t) - TEE signature.
            tee_enclave: TEE enclave for verification.

        Returns:
            True if verification succeeds and data is stored.

        Paper: Phase V, Step 1 - "Cloud stores (T_i(t), σ_i(t)) only after
               successful signature verification."
        """
        # Compute hash of aggregation package
        hash_data = compute_hash((
            str(aggregation_package.get('final_aggregate', '')),
            str(aggregation_package.get('mode', '')),
            str(aggregation_package.get('reliability', '')),
            str(aggregation_package.get('recovery_status', ''))
        ))

        # Verify signature
        verified = tee_enclave.verify_signature(hash_data, signature)

        log_entry = {
            'epoch': epoch,
            'fog_node_id': fog_node_id,
            'verified': verified,
            'mode': aggregation_package.get('mode', 'Unknown')
        }
        self.verification_log.append(log_entry)

        if verified:
            # Store the aggregation package
            if epoch not in self.storage:
                self.storage[epoch] = {}
            self.storage[epoch][fog_node_id] = {
                'package': aggregation_package,
                'signature': signature
            }

        return verified

    def store_aggregate(self, fog_node_id: int, epoch: int,
                         aggregation_package: dict):
        """
        Directly store an aggregation package (simplified path without
        signature verification for simulation efficiency).

        Args:
            fog_node_id: ID of the submitting fog node.
            epoch: Current aggregation epoch.
            aggregation_package: T_i(t) data.
        """
        if epoch not in self.storage:
            self.storage[epoch] = {}
        self.storage[epoch][fog_node_id] = {
            'package': aggregation_package,
            'signature': None
        }

    def get_stored_epochs(self) -> List[int]:
        """Get list of all stored epoch indices."""
        return sorted(self.storage.keys())

    def get_epoch_data(self, epoch: int) -> Optional[Dict[int, dict]]:
        """Get all stored data for a specific epoch."""
        return self.storage.get(epoch)

    def get_stats(self) -> dict:
        """Get cloud server statistics."""
        total_verified = sum(1 for v in self.verification_log if v['verified'])
        total_failed = sum(1 for v in self.verification_log if not v['verified'])
        return {
            'total_epochs_stored': len(self.storage),
            'total_verifications': len(self.verification_log),
            'verified_success': total_verified,
            'verified_failed': total_failed
        }

    def __repr__(self):
        return f"CloudServer(epochs_stored={len(self.storage)})"
